version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keyclock
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped 
    environment:
      - PGADMIN_DEFAULT_EMAIL=wulab@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ytwu35415
    ports:
      - "5555:80"
  keycloak:
    image: jennyhuoh/keycloak:latest
    restart: unless-stopped
    depends_on:
      - "postgres"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - DB_DATABASE=keyclock
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DB_ADDR=postgres
      - DB_VENDOR=POSTGRES
      - DB_PORT=5432
      - DEBUG=true
    volumes:
      - type: bind
        source: /theme directory 
        target: /opt/jboss/keycloak/themes/serendipity
    ports:
      - 8080:8080
  nginx_rproxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
    - 80:80
    - 443:443



